// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXx98v8BiS34Dh8umFiKRTpZG75fMnOZg',
    appId: '1:792093734940:android:c8e50d21fd2f1917e087d9',
    messagingSenderId: '792093734940',
    projectId: 'pickndream-dashboard',
    storageBucket: 'pickndream-dashboard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfEWdb3AMVXiVJAxOh2tRV7vGGv3fSqL0',
    appId: '1:792093734940:ios:7ab6cf3271ca100be087d9',
    messagingSenderId: '792093734940',
    projectId: 'pickndream-dashboard',
    storageBucket: 'pickndream-dashboard.firebasestorage.app',
    iosBundleId: 'com.pickndream.pickndream',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqE8-qRaz6edgfZEfW-H5qbhaitsEsv14',
    appId: '1:792093734940:web:fced7cec6d809fc9e087d9',
    messagingSenderId: '792093734940',
    projectId: 'pickndream-dashboard',
    authDomain: 'pickndream-dashboard.firebaseapp.com',
    storageBucket: 'pickndream-dashboard.firebasestorage.app',
  );

}